import { excerpt, p } from "../blocks";
import { poemOpenSettings } from "../settings";
import type { PoemAnalysisContent } from "../types";
export const chicagoPoem: PoemAnalysisContent = {
 slug:"chicago",status:"ready",poemTitle:"Chicago",author:"Carl Sandburg",yearPublished:1914,publicDomainBasis:"First published in Poetry in 1914, before the US public-domain cutoff.",title:"Chicago Analysis & Meaning — Carl Sandburg — lyriic",description:"Analysis of Sandburg’s free-verse city poem, labor, pride, violence, and resilience.",h1:"Chicago analysis",intro:"Sandburg admits Chicago’s violence and hunger before celebrating its labor, energy, and civic pride.",
 fullTextSource:{label:"Chicago",url:"https://www.poetryfoundation.org/poetrymagazine/poems/12840/chicago",publisher:"Poetry Foundation"},editorSettings:poemOpenSettings(),
 summary:[p("The speaker names Chicago through industrial occupations, concedes its vice and brutality, then answers its critics with an image of a laughing worker."),excerpt(`Hog Butcher for the World,
Tool Maker, Stacker of Wheat,
Player with Railroads and the Nation's Freight Handler;`),p("The city’s greatness is grounded in work rather than polished respectability.")],
 meaning:[p("The defense persuades because it does not pretend Chicago is innocent. Pride and social damage coexist in the same urban body."),excerpt(`Come and show me another city with lifted head singing so proud to be alive and coarse and strong and cunning.`),p("The final laughter makes resilience a public, physical act.",["sandburg-nps"])],
 themes:[{theme:"Industrial labor",blocks:[p("The opening catalogue identifies Chicago through slaughtering, tools, grain, and freight.")]},{theme:"Clear-eyed civic pride",blocks:[p("Crime and hunger are admitted before the speaker celebrates the city.")]},{theme:"Youth and resilience",blocks:[excerpt(`Building, breaking, rebuilding,
Under the smoke, dust all over his mouth, laughing with white teeth,`),p("Rebuilding turns hardship into continued motion.")]}],
 formAndMeter:[p("This is free verse with no fixed stanza, rhyme scheme, or regular meter. Its form comes from catalogues, punctuation, and changing line length."),p("Long sentences are interrupted by one-word action lines such as “Shoveling” and “Laughing!”, creating a physical rhythm.")],
 literaryDevices:[{device:"Personification",blocks:[excerpt(`here is a tall bold slugger set vivid against the little soft cities;`),p("Chicago becomes a working fighter with sweat, teeth, ribs, and laughter.")]},{device:"Catalogue",blocks:[excerpt(`Bareheaded,
Shoveling,
Wrecking,`),p("Accumulated occupations make civic identity collective.")]},{device:"Repetition",blocks:[excerpt(`Laughing!
Laughing the stormy, husky, brawling laughter of Youth,`),p("Repeated laughter gathers force at the close.")]}],
 historicalContext:[p("Sandburg moved to Chicago in 1912 and worked as a reporter. The National Park Service connects his early writing with labor rights and unsafe working conditions.",["sandburg-nps"]),p("Harriet Monroe published the poem in Poetry in March 1914; it later appeared in Chicago Poems (1916).",["sandburg-history"])],
 citations:[{id:"poem-text-chicago",source:"Poetry Foundation",url:"https://www.poetryfoundation.org/poetrymagazine/poems/12840/chicago"},{id:"sandburg-nps",source:"National Park Service",quote:"Sandburg’s early writings tackled social justice, human dignity, and labor rights.",url:"https://www.nps.gov/articles/000/carl-sandburg-and-chicago.htm"},{id:"sandburg-history",source:"Carl Sandburg Home National Historic Site",quote:"Chicago became one of the best known works of 20th century American literature.",url:"https://www.nps.gov/carl/learn/historyculture/chicago.htm"},{id:"chicago-analysis",source:"EBSCO Research Starters",url:"https://www.ebsco.com/research-starters/literature-and-writing/chicago-carl-sandburg"}],
 criticalViews:[{citeId:"sandburg-nps"},{citeId:"sandburg-history"}],faqs:[{q:"What is the meaning?",plain:"Chicago celebrates industrial strength and working people without denying crime, poverty, or corruption."},{q:"Why Big Shoulders?",plain:"The phrase personifies the city as a strong laborer carrying collective work and burden."},{q:"What form is used?",plain:"Free verse shaped by repetition, catalogues, and long and short lines."}],cta:"Read the poem in the zen editor",
};
