import { excerpt, p } from "../blocks";
import { poemOpenSettings } from "../settings";
import type { PoemAnalysisContent } from "../types";
export const doubtNoMoreThatOberonPoem: PoemAnalysisContent = {
 slug:"doubt-no-more-that-oberon",status:"ready",poemTitle:"Doubt No More That Oberon",author:"Edna St. Vincent Millay",yearPublished:1921,publicDomainBasis:"Published in Second April in 1921, before the US public-domain cutoff.",title:"Doubt No More That Oberon Analysis & Meaning — Edna St. Vincent Millay — lyriic",description:"Analysis of Millay’s mythic spring poem, wonder, despair, and renewal.",h1:"Doubt No More That Oberon analysis",intro:"Millay uses myth and spring to argue that wonder can persist in a damaged age.",fullTextSource:{label:"Second April",url:"https://monadnock.net/millay/",publisher:"Monadnock Valley Press"},editorSettings:poemOpenSettings({showCounts:true,showRulers:false}),
 summary:[p("The speaker insists that Oberon and Pan should not be dismissed as childish inventions. Against a sorrowful present, ordinary spring becomes evidence of persistence.",["poem-text-millay"]),excerpt(`Doubt no more that Oberon—
Never doubt that Pan
Lived, and played a reed,`),p("The dogwood and returning birds replace vanished fauns and fays as modest signs of wonder.")],
 meaning:[p("Wonder survives not as perfect myth but as recurring natural life. The poem’s hope is limited: flowers bear no fruit and birds cannot sing, yet they return."),excerpt(`Still the dog-wood dares to raise—
Healthy tree, with trunk and root—
Ivory bowls that bear no fruit,`),p("“Dare” makes seasonal growth a resistance to despair.",["millay-second-april"])],
 themes:[{theme:"Wonder versus despair",blocks:[p("The imperative “Doubt no more” treats belief as an active answer to cynicism.")]},{theme:"Nature’s renewal",blocks:[excerpt(`And the starlings and the jays—
Birds that cannot even sing—
Dare to come again in spring!`),p("Imperfect return becomes proof of persistence.")]},{theme:"Beauty with mortality",blocks:[p("Death is acknowledged directly before the poem turns to growth, so hope does not erase loss.")]}],
 formAndMeter:[p("A sixteen-line single-stanza lyric uses short, irregular lines and audible but varied rhyme."),p("Repeated verbs—“Lived” and “Dare”—supply structural unity more than a fixed meter does.")],
 literaryDevices:[{device:"Mythological allusion",blocks:[excerpt(`Never doubt that Pan
Lived, and played a reed, and ran`),p("Oberon and Pan enlarge a spring scene into a debate about lost enchantment.")]},{device:"Personification",blocks:[excerpt(`Still the dog-wood dares to raise—`),p("“Dares” makes growth sound like deliberate defiance.")]},{device:"Understatement",blocks:[excerpt(`Birds that cannot even sing—`),p("Compromised beauty makes the poem’s hope demanding rather than sentimental.")]}],
 historicalContext:[p("The poem appeared in Second April (1921), a collection shaped by postwar and post-pandemic mortality; contemporary readers described its gloom as nearly outweighing its lyricism.",["millay-second-april"]),p("Millay’s Pan belongs to a literary conversation about whether pagan nature figures could survive in modernity.")],
 citations:[{id:"poem-text-millay",source:"Monadnock Valley Press",url:"https://monadnock.net/millay/"},{id:"millay-second-april",source:"Los Angeles Review of Books",author:"V. M. Braganza",quote:"they breathed a gloom so unmitigated as almost to outweigh their lyrical quality.",url:"https://lareviewofbooks.org/blog/essays/second-april/"},{id:"millay-pan",source:"WSFA Journal",author:"Thomas Burnett Swann",quote:"Pan was an insider and not an outsider",url:"https://fanac.org/fanzines/WSFA_Journal/WSFA_Journal68.pdf"},{id:"millay-poetry",source:"Literary Ladies Guide",url:"https://www.literaryladiesguide.com/classic-women-authors-poetry/second-april-by-edna-st-vincent-millay-1921-full-text/"}],
 criticalViews:[{citeId:"millay-second-april"},{citeId:"millay-pan"}],faqs:[{q:"What is the meaning?",plain:"The poem argues that wonder and renewal remain possible even in a sorrowful age."},{q:"What are its themes?",plain:"Wonder, despair, natural renewal, and beauty alongside mortality."},{q:"What form does it use?",plain:"A sixteen-line single-stanza lyric with irregular rhythm and recurring rhyme."}],cta:"Write with this poem’s open form in the editor",
};
