/** Generated by scripts/build-pronunciation.mjs — do not edit. */

/** Apostrophe/elided form → citation lemma for meter-fit alt lookup. */
export const ELISION_BRIDGES: Readonly<Record<string, string>> = {
  "dang'rous": "dangerous",
  "am'rous": "amorous",
  "heav'n": "heaven",
  "e'en": "even",
  "ev'ry": "every",
  "ne'er": "never",
  "o'er": "over",
  "th'": "the",
} as const;
