/**
 * Source list scraped from americanliterature.com/poetry-for-students/
 * (Wayback capture 2026-06-09). Copyright screening: US public domain =
 * first published 1930 or earlier (as of 2026).
 */

import type { PoemCatalogEntry } from "./types";

export const POEM_CATALOG: PoemCatalogEntry[] = [
  {
    slug: "he-wishes-for-the-cloths-of-heaven",
    poemTitle: "He Wishes for the Cloths of Heaven",
    author: "William Butler Yeats",
    yearPublished: 1899,
    copyrightStatus: "public-domain",
  },
  {
    slug: "o-captain-my-captain",
    poemTitle: "O Captain! My Captain!",
    author: "Walt Whitman",
    yearPublished: 1865,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-road-not-taken",
    poemTitle: "The Road Not Taken",
    author: "Robert Frost",
    yearPublished: 1916,
    copyrightStatus: "public-domain",
  },
  {
    slug: "stopping-by-woods-on-a-snowy-evening",
    poemTitle: "Stopping by Woods on a Snowy Evening",
    author: "Robert Frost",
    yearPublished: 1923,
    copyrightStatus: "public-domain",
  },
  {
    slug: "fire-and-ice",
    poemTitle: "Fire and Ice",
    author: "Robert Frost",
    yearPublished: 1920,
    copyrightStatus: "public-domain",
  },
  {
    slug: "mending-wall",
    poemTitle: "Mending Wall",
    author: "Robert Frost",
    yearPublished: 1914,
    copyrightStatus: "public-domain",
  },
  {
    slug: "to-the-spring",
    poemTitle: "To the Spring. Or of the Fables of the Ancients.",
    author: "Unknown / traditional",
    yearPublished: null,
    copyrightStatus: "verify",
    notes: "Identify author and first publication before authoring.",
  },
  {
    slug: "pastoral",
    poemTitle: "Pastoral",
    author: "William Carlos Williams",
    yearPublished: 1917,
    copyrightStatus: "public-domain",
  },
  {
    slug: "because-i-could-not-stop-for-death",
    poemTitle: "Because I Could Not Stop for Death",
    author: "Emily Dickinson",
    yearPublished: 1890,
    copyrightStatus: "public-domain",
    notes: "First published posthumously 1890; confirm Johnson/Franklin numbering in sources.",
  },
  {
    slug: "do-not-go-gentle-into-that-good-night",
    poemTitle: "Do not go gentle into that good night",
    author: "Dylan Thomas",
    yearPublished: 1951,
    copyrightStatus: "copyrighted-skip",
  },
  {
    slug: "paris-in-spring",
    poemTitle: "Paris in Spring",
    author: "Sara Teasdale",
    yearPublished: 1915,
    copyrightStatus: "verify",
    notes: "Confirm author and year; Teasdale has a poem of this title.",
  },
  {
    slug: "a-thing-of-beauty-is-a-joy-forever",
    poemTitle: "A Thing of Beauty Is a Joy Forever",
    author: "John Keats",
    yearPublished: 1818,
    copyrightStatus: "public-domain",
    notes: "Opening of Endymion — treat as excerpt of a long poem.",
  },
  {
    slug: "the-song-of-hiawatha",
    poemTitle: "The Song of Hiawatha",
    author: "Henry Wadsworth Longfellow",
    yearPublished: 1855,
    copyrightStatus: "public-domain",
    notes: "Long epic — use a famous excerpt only.",
  },
  {
    slug: "chuang-tzu-and-the-butterfly",
    poemTitle: "Chuang Tzu and the Butterfly",
    author: "Li Bai",
    yearPublished: null,
    copyrightStatus: "verify",
    notes: "Chinese original ancient; only use a pre-1931 English translation (or skip).",
  },
  {
    slug: "when-lilacs-last-in-the-dooryard-bloomd",
    poemTitle: "When Lilacs Last in the Dooryard Bloom'd",
    author: "Walt Whitman",
    yearPublished: 1865,
    copyrightStatus: "public-domain",
    notes: "Long elegy — use a famous excerpt.",
  },
  {
    slug: "the-walrus-and-the-carpenter",
    poemTitle: "The Walrus and the Carpenter",
    author: "Lewis Carroll",
    yearPublished: 1871,
    copyrightStatus: "public-domain",
  },
  {
    slug: "jabberwocky",
    poemTitle: "Jabberwocky",
    author: "Lewis Carroll",
    yearPublished: 1871,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-more-loving-one",
    poemTitle: "The More Loving One",
    author: "W. H. Auden",
    yearPublished: 1957,
    copyrightStatus: "copyrighted-skip",
  },
  {
    slug: "the-raven",
    poemTitle: "The Raven",
    author: "Edgar Allan Poe",
    yearPublished: 1845,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-song-of-wandering-aengus",
    poemTitle: "The Song of Wandering Aengus",
    author: "William Butler Yeats",
    yearPublished: 1899,
    copyrightStatus: "public-domain",
  },
  {
    slug: "hope-is-the-thing-with-feathers",
    poemTitle: "Hope Is the Thing with Feathers",
    author: "Emily Dickinson",
    yearPublished: 1891,
    copyrightStatus: "public-domain",
  },
  {
    slug: "invictus",
    poemTitle: "Invictus",
    author: "William Ernest Henley",
    yearPublished: 1875,
    copyrightStatus: "public-domain",
  },
  {
    slug: "acquainted-with-the-night",
    poemTitle: "Acquainted with the Night",
    author: "Robert Frost",
    yearPublished: 1928,
    copyrightStatus: "public-domain",
  },
  {
    slug: "little-women-poem",
    poemTitle: "Little Women (poem)",
    author: "Louisa May Alcott",
    yearPublished: 1868,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-battle-hymn-of-the-republic",
    poemTitle: "The Battle Hymn of the Republic",
    author: "Julia Ward Howe",
    yearPublished: 1862,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-minstrel-boy",
    poemTitle: "The Minstrel Boy",
    author: "Thomas Moore",
    yearPublished: 1813,
    copyrightStatus: "public-domain",
  },
  {
    slug: "big-grand-coolee-dam",
    poemTitle: "Big Grand Coolee Dam",
    author: "Woody Guthrie",
    yearPublished: 1941,
    copyrightStatus: "copyrighted-skip",
    notes: "Grand Coulee Dam / Woody Guthrie — still under copyright.",
  },
  {
    slug: "first-fig",
    poemTitle: "First Fig",
    author: "Edna St. Vincent Millay",
    yearPublished: 1920,
    copyrightStatus: "public-domain",
  },
  {
    slug: "ode-to-silence",
    poemTitle: "Ode to Silence",
    author: "Edna St. Vincent Millay",
    yearPublished: 1921,
    copyrightStatus: "public-domain",
  },
  {
    slug: "in-flanders-fields",
    poemTitle: "In Flanders Fields",
    author: "John McCrae",
    yearPublished: 1915,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-charge-of-the-light-brigade",
    poemTitle: "The Charge of the Light Brigade",
    author: "Alfred, Lord Tennyson",
    yearPublished: 1854,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-second-coming",
    poemTitle: "The Second Coming",
    author: "William Butler Yeats",
    yearPublished: 1920,
    copyrightStatus: "public-domain",
  },
  {
    slug: "perplexed-music",
    poemTitle: "Perplexed Music",
    author: "Elizabeth Barrett Browning",
    yearPublished: 1844,
    copyrightStatus: "public-domain",
  },
  {
    slug: "paul-reveres-ride",
    poemTitle: "Paul Revere's Ride",
    author: "Henry Wadsworth Longfellow",
    yearPublished: 1860,
    copyrightStatus: "public-domain",
  },
  {
    slug: "goliath-and-david",
    poemTitle: "Goliath and David",
    author: "Robert Graves",
    yearPublished: 1916,
    copyrightStatus: "public-domain",
  },
  {
    slug: "nothing-will-die",
    poemTitle: "Nothing Will Die",
    author: "Alfred, Lord Tennyson",
    yearPublished: 1830,
    copyrightStatus: "public-domain",
  },
  {
    slug: "i-too-sing-america",
    poemTitle: "I, Too, Sing America",
    author: "Langston Hughes",
    yearPublished: 1926,
    copyrightStatus: "public-domain",
  },
  {
    slug: "song-of-myself",
    poemTitle: "Song of Myself",
    author: "Walt Whitman",
    yearPublished: 1855,
    copyrightStatus: "public-domain",
    notes: "Long — use a famous excerpt (e.g. section 1 / 6 / 52).",
  },
  {
    slug: "ozymandias",
    poemTitle: "Ozymandias",
    author: "Percy Bysshe Shelley",
    yearPublished: 1818,
    copyrightStatus: "public-domain",
  },
  {
    slug: "ode-to-the-west-wind",
    poemTitle: "Ode to the West Wind",
    author: "Percy Bysshe Shelley",
    yearPublished: 1820,
    copyrightStatus: "public-domain",
  },
  {
    slug: "there-will-come-soft-rains",
    poemTitle: "There Will Come Soft Rains",
    author: "Sara Teasdale",
    yearPublished: 1920,
    copyrightStatus: "public-domain",
  },
  {
    slug: "to-the-virgins-to-make-much-of-time",
    poemTitle: "To the Virgins, to Make Much of Time",
    author: "Robert Herrick",
    yearPublished: 1648,
    copyrightStatus: "public-domain",
  },
  {
    slug: "go-and-catch-a-falling-star",
    poemTitle: "Song: Go and catch a falling star",
    author: "John Donne",
    yearPublished: 1633,
    copyrightStatus: "public-domain",
  },
  {
    slug: "each-and-all",
    poemTitle: "Each and All",
    author: "Ralph Waldo Emerson",
    yearPublished: 1839,
    copyrightStatus: "public-domain",
  },
  {
    slug: "in-praise-of-solid-people",
    poemTitle: "In Praise of Solid People",
    author: "C. S. Lewis",
    yearPublished: 1919,
    copyrightStatus: "public-domain",
    notes: "From Spirits in Bondage (1919) — PD in US.",
  },
  {
    slug: "new-hampshire",
    poemTitle: "New Hampshire",
    author: "Robert Frost",
    yearPublished: 1923,
    copyrightStatus: "public-domain",
    notes: "Title poem of the 1923 volume — long; excerpt as needed.",
  },
  {
    slug: "how-do-i-love-thee",
    poemTitle: "How Do I Love Thee?",
    author: "Elizabeth Barrett Browning",
    yearPublished: 1850,
    copyrightStatus: "public-domain",
    notes: "Sonnets from the Portuguese 43.",
  },
  {
    slug: "all-the-worlds-a-stage",
    poemTitle: "All the World's a Stage",
    author: "William Shakespeare",
    yearPublished: 1623,
    copyrightStatus: "public-domain",
    notes: "Speech from As You Like It (Act II, Scene VII).",
  },
  {
    slug: "my-heart-and-i",
    poemTitle: "My Heart and I",
    author: "Elizabeth Barrett Browning",
    yearPublished: 1860,
    copyrightStatus: "public-domain",
  },
  {
    slug: "sonnet-73",
    poemTitle: "Sonnet 73",
    author: "William Shakespeare",
    yearPublished: 1609,
    copyrightStatus: "public-domain",
  },
  {
    slug: "loveliest-of-trees",
    poemTitle: "Loveliest of Trees",
    author: "A. E. Housman",
    yearPublished: 1896,
    copyrightStatus: "public-domain",
    notes: "A Shropshire Lad II.",
  },
  {
    slug: "doubt-no-more-that-oberon",
    poemTitle: "Doubt No More That Oberon",
    author: "Edna St. Vincent Millay",
    yearPublished: 1921,
    copyrightStatus: "public-domain",
  },
  {
    slug: "a-day-of-sunshine",
    poemTitle: "A Day of Sunshine",
    author: "Henry Wadsworth Longfellow",
    yearPublished: 1863,
    copyrightStatus: "public-domain",
  },
  {
    slug: "she-walks-in-beauty",
    poemTitle: "She Walks in Beauty",
    author: "Lord Byron",
    yearPublished: 1815,
    copyrightStatus: "public-domain",
  },
  {
    slug: "our-country",
    poemTitle: "Our Country",
    author: "Julia Ward Howe",
    yearPublished: 1861,
    copyrightStatus: "verify",
  },
  {
    slug: "a-nameless-grave",
    poemTitle: "A Nameless Grave",
    author: "Henry Wadsworth Longfellow",
    yearPublished: 1864,
    copyrightStatus: "public-domain",
  },
  {
    slug: "daybreak",
    poemTitle: "Daybreak",
    author: "Jack London",
    yearPublished: null,
    copyrightStatus: "verify",
    notes: "Confirm London poem text and first publication year.",
  },
  {
    slug: "ebb-tide",
    poemTitle: "Ebb Tide",
    author: "Sara Teasdale",
    yearPublished: 1915,
    copyrightStatus: "verify",
  },
  {
    slug: "when-you-are-old",
    poemTitle: "When You Are Old",
    author: "William Butler Yeats",
    yearPublished: 1893,
    copyrightStatus: "public-domain",
  },
  {
    slug: "magdalen-walks",
    poemTitle: "Magdalen Walks",
    author: "Oscar Wilde",
    yearPublished: 1881,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-river-merchants-wife",
    poemTitle: "The River-Merchant's Wife: A Letter",
    author: "Ezra Pound (after Li Bai)",
    yearPublished: 1915,
    copyrightStatus: "public-domain",
    notes: "Pound's Cathay (1915) translation — PD in US.",
  },
  {
    slug: "a-poem-of-changgan",
    poemTitle: "A Poem of Changgan",
    author: "Li Bai",
    yearPublished: null,
    copyrightStatus: "verify",
    notes: "Likely duplicate of River-Merchant's Wife source text; pick one PD translation or skip as duplicate.",
  },
  {
    slug: "a-valediction-forbidding-mourning",
    poemTitle: "A Valediction: Forbidding Mourning",
    author: "John Donne",
    yearPublished: 1633,
    copyrightStatus: "public-domain",
  },
  {
    slug: "song-of-the-witches",
    poemTitle: "Song of the Witches",
    author: "William Shakespeare",
    yearPublished: 1623,
    copyrightStatus: "public-domain",
    notes: "Macbeth Act IV Scene I ('Double, double toil and trouble').",
  },
  {
    slug: "goblin-feet",
    poemTitle: "Goblin Feet",
    author: "J. R. R. Tolkien",
    yearPublished: 1915,
    copyrightStatus: "public-domain",
    notes: "Published in Oxford Poetry 1915 — PD in US.",
  },
  {
    slug: "oily-weather",
    poemTitle: "Oily Weather",
    author: "Unknown",
    yearPublished: null,
    copyrightStatus: "verify",
    notes: "Identify author before authoring; skip if copyrighted.",
  },
  {
    slug: "ultimately",
    poemTitle: "Ultimately",
    author: "Ernest Hemingway",
    yearPublished: 1923,
    copyrightStatus: "public-domain",
    notes: "From Three Stories and Ten Poems (1923).",
  },
  {
    slug: "we-grow-accustomed-to-the-dark",
    poemTitle: "We Grow Accustomed to the Dark",
    author: "Emily Dickinson",
    yearPublished: 1890,
    copyrightStatus: "public-domain",
  },
  {
    slug: "a-november-night",
    poemTitle: "A November Night",
    author: "Sara Teasdale",
    yearPublished: 1915,
    copyrightStatus: "public-domain",
  },
  {
    slug: "a-pinch-of-salt",
    poemTitle: "A Pinch of Salt",
    author: "Robert Graves",
    yearPublished: 1916,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-love-song-of-j-alfred-prufrock",
    poemTitle: "The Love Song of J. Alfred Prufrock",
    author: "T. S. Eliot",
    yearPublished: 1915,
    copyrightStatus: "public-domain",
  },
  {
    slug: "ode-on-a-grecian-urn",
    poemTitle: "Ode on a Grecian Urn",
    author: "John Keats",
    yearPublished: 1820,
    copyrightStatus: "public-domain",
  },
  {
    slug: "i-taught-myself-to-live-simply",
    poemTitle: "I Taught Myself to Live Simply",
    author: "Anna Akhmatova",
    yearPublished: null,
    copyrightStatus: "copyrighted-skip",
    notes: "Modern English translation almost certainly still under copyright.",
  },
  {
    slug: "i-wandered-lonely-as-a-cloud",
    poemTitle: "I Wandered Lonely as a Cloud",
    author: "William Wordsworth",
    yearPublished: 1807,
    copyrightStatus: "public-domain",
  },
  {
    slug: "winter-in-the-boulevard",
    poemTitle: "Winter in the Boulevard",
    author: "D. H. Lawrence",
    yearPublished: 1918,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-world-is-too-much-with-us",
    poemTitle: "The World Is Too Much with Us",
    author: "William Wordsworth",
    yearPublished: 1807,
    copyrightStatus: "public-domain",
  },
  {
    slug: "dreams",
    poemTitle: "Dreams",
    author: "Langston Hughes",
    yearPublished: 1922,
    copyrightStatus: "public-domain",
  },
  {
    slug: "let-america-be-america-again",
    poemTitle: "Let America Be America Again",
    author: "Langston Hughes",
    yearPublished: 1936,
    copyrightStatus: "copyrighted-skip",
  },
  {
    slug: "the-waste-land",
    poemTitle: "The Waste Land",
    author: "T. S. Eliot",
    yearPublished: 1922,
    copyrightStatus: "public-domain",
    notes: "Long — use a famous excerpt (e.g. opening of Part I).",
  },
  {
    slug: "awake-young-men-of-england",
    poemTitle: "Awake! Young Men of England",
    author: "George Orwell",
    yearPublished: 1914,
    copyrightStatus: "public-domain",
  },
  {
    slug: "a-little-poem",
    poemTitle: "A Little Poem",
    author: "George Orwell",
    yearPublished: 1935,
    copyrightStatus: "copyrighted-skip",
    notes: "Orwell's 'A happy vicar I might have been' (~1935) — still copyrighted.",
  },
  {
    slug: "the-rape-of-the-lock",
    poemTitle: "The Rape of the Lock",
    author: "Alexander Pope",
    yearPublished: 1712,
    copyrightStatus: "public-domain",
    notes: "Long mock-epic — use a famous excerpt (Canto I opening or Canto III).",
  },
  {
    slug: "bless-god-he-went-as-soldiers",
    poemTitle: "Bless God, he went as soldiers",
    author: "Emily Dickinson",
    yearPublished: 1890,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-rime-of-the-ancient-mariner",
    poemTitle: "The Rime of the Ancient Mariner",
    author: "Samuel Taylor Coleridge",
    yearPublished: 1798,
    copyrightStatus: "public-domain",
    notes: "Long — use a famous excerpt.",
  },
  {
    slug: "i-cannot-live-with-you",
    poemTitle: "I cannot live with You",
    author: "Emily Dickinson",
    yearPublished: 1890,
    copyrightStatus: "public-domain",
    notes: "Source list title 'I Cannot Live Without You' — standard title is 'I cannot live with You'.",
  },
  {
    slug: "if",
    poemTitle: "If—",
    author: "Rudyard Kipling",
    yearPublished: 1910,
    copyrightStatus: "public-domain",
  },
  {
    slug: "a-dream-within-a-dream",
    poemTitle: "A Dream Within a Dream",
    author: "Edgar Allan Poe",
    yearPublished: 1849,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-ballad-of-the-harp-weaver",
    poemTitle: "The Ballad of the Harp-Weaver",
    author: "Edna St. Vincent Millay",
    yearPublished: 1922,
    copyrightStatus: "public-domain",
  },
  {
    slug: "love-and-friendship",
    poemTitle: "Love and Friendship",
    author: "Emily Brontë",
    yearPublished: 1846,
    copyrightStatus: "public-domain",
  },
  {
    slug: "a-poison-tree",
    poemTitle: "A Poison Tree",
    author: "William Blake",
    yearPublished: 1794,
    copyrightStatus: "public-domain",
  },
  {
    slug: "to-the-friend-of-my-youth",
    poemTitle: "To the Friend of My Youth: To Kitty",
    author: "Kate Chopin",
    yearPublished: 1900,
    copyrightStatus: "verify",
  },
  {
    slug: "paradise-lost",
    poemTitle: "Paradise Lost",
    author: "John Milton",
    yearPublished: 1667,
    copyrightStatus: "public-domain",
    notes: "Epic — use a famous excerpt (Book I opening).",
  },
  {
    slug: "the-tyger",
    poemTitle: "The Tyger",
    author: "William Blake",
    yearPublished: 1794,
    copyrightStatus: "public-domain",
  },
  {
    slug: "we-wear-the-mask",
    poemTitle: "We Wear the Mask",
    author: "Paul Laurence Dunbar",
    yearPublished: 1896,
    copyrightStatus: "public-domain",
  },
  {
    slug: "richard-cory",
    poemTitle: "Richard Cory",
    author: "Edwin Arlington Robinson",
    yearPublished: 1897,
    copyrightStatus: "public-domain",
  },
  {
    slug: "chicago",
    poemTitle: "Chicago",
    author: "Carl Sandburg",
    yearPublished: 1914,
    copyrightStatus: "public-domain",
  },
  {
    slug: "fog",
    poemTitle: "Fog",
    author: "Carl Sandburg",
    yearPublished: 1916,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-red-wheelbarrow",
    poemTitle: "The Red Wheelbarrow",
    author: "William Carlos Williams",
    yearPublished: 1923,
    copyrightStatus: "public-domain",
  },
  {
    slug: "this-is-just-to-say",
    poemTitle: "This Is Just To Say",
    author: "William Carlos Williams",
    yearPublished: 1934,
    copyrightStatus: "copyrighted-skip",
  },
  {
    slug: "thirteen-ways-of-looking-at-a-blackbird",
    poemTitle: "Thirteen Ways of Looking at a Blackbird",
    author: "Wallace Stevens",
    yearPublished: 1917,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-highwayman",
    poemTitle: "The Highwayman",
    author: "Alfred Noyes",
    yearPublished: 1906,
    copyrightStatus: "public-domain",
  },
  {
    slug: "the-cremation-of-sam-mcgee",
    poemTitle: "The Cremation of Sam McGee",
    author: "Robert W. Service",
    yearPublished: 1907,
    copyrightStatus: "public-domain",
  },
];

const BY_SLUG = new Map(POEM_CATALOG.map((e) => [e.slug, e] as const));

export function getCatalogEntry(slug: string): PoemCatalogEntry | undefined {
  return BY_SLUG.get(slug);
}

export function listPublicDomainCatalog(): PoemCatalogEntry[] {
  return POEM_CATALOG.filter((e) => e.copyrightStatus === "public-domain");
}

export function listSkippedCatalog(): PoemCatalogEntry[] {
  return POEM_CATALOG.filter((e) => e.copyrightStatus === "copyrighted-skip");
}

export function listVerifyCatalog(): PoemCatalogEntry[] {
  return POEM_CATALOG.filter((e) => e.copyrightStatus === "verify");
}
